##
#	SWISH++
#	man/man4/Makefile
#
#	Copyright (C) 1998  Paul J. Lucas
#
#	This program is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; either version 2 of the License, or
#	(at your option) any later version.
# 
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
# 
#	You should have received a copy of the GNU General Public License
#	along with this program; if not, write to the Free Software
#	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
##

########## You shouldn't have to change anything below this line. #############

ROOT=		../..
include		$(ROOT)/config/config.mk

SECT=		4
PAGES=		swish++.conf.$(SECT) swish++.index.$(SECT)
TARGET_TXT=	swish++.conf.txt swish++.index.txt
TARGET_PDF=	swish++.conf.pdf swish++.index.pdf
TARGET_PS=	swish++.conf.ps swish++.index.ps

include		$(ROOT)/config/man.mk
