#! /bin/sh
##
#       SWISH++
#       config/init_modules-sh
#
#       Copyright (C) 2001-2015  Paul J. Lucas
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
##

cat <<END
/*
**      SWISH++
**      src/init_modules.cpp
**
**      Copyright (C) 2001-2015  Paul J. Lucas
**
**      This program is free software; you can redistribute it and/or modify
**      it under the terms of the GNU General Public License as published by
**      the Free Software Foundation; either version 2 of the License, or
**      (at your option) any later version.
**
**      This program is distributed in the hope that it will be useful,
**      but WITHOUT ANY WARRANTY; without even the implied warranty of
**      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**      GNU General Public License for more details.
**
**      You should have received a copy of the GNU General Public License
**      along with this program; if not, write to the Free Software
**      Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

/*
**      Note: This file was automatically generated on:
**      `date`.
*/

// local
#include "config.h"
#include "indexer.h"
END

ident() {
  basename $HEADER | sed -e 's/\.h$//' -e 's/mod_/WITH_/' | tr '[a-z]' '[A-Z]'
}

for HEADER in mod/*/mod_*.h
do
  IDENT=`ident $HEADER`
  cat <<END
#ifdef $IDENT
#include "$HEADER"
#endif /* $IDENT */
END
done

cat <<END

/**
 * This function is a place to bundle together the construction of the
 * singleton instances of indexer modules.  The base indexer() constructor will
 * add pointers to them into the static mod_name-to-instance map.
 */
void indexer::init_modules() {
END

for HEADER in mod/*/mod_*.h
do
  CLASS=`fgrep " : public indexer" $HEADER | sed 's/.*class  *\([A-Za-z_][A-Za-z0-9_]*\).*/\1/'`
  IDENT=`ident $HEADER`
  cat <<END
#ifdef $IDENT
  static $CLASS ${CLASS}_instance;
#endif /* $IDENT */
END
done

cat <<END
  // The plain text indexer is initialized in indexer::map_ref().
}
END

# vim:set et sw=2 ts=2:
